volumes:
  db-data:
  chrisolsen-goweb-mod_cache:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
  app_net:

services:
  public:
    build: 
      context: .
      dockerfile: Dockerfile.public.prod
    volumes:
      - .:/app
      - chrisolsen-goweb-mod_cache:/go/pkg/mod

    networks:
      - caddy_net
      - app_net

  admin:
    build: 
      context: .
      dockerfile: Dockerfile.admin.prod
    volumes:
      - .:/app
      - chrisolsen-goweb-mod_cache:/go/pkg/mod

    networks:
      - caddy_net
      - app_net

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:3000"
      - "443:3000"
      - "443:3000/udp"
      - "8080:3030"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
