volumes:
  postgres-data:
  chrisolsen-goweb-mod_cache:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
  app_net:

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - ../.env
    volumes:
      - ../:/app
      - chrisolsen-goweb-mod_cache:/go/pkg/mod
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - caddy_net
      - app_net

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/.config/Caddyfile.dev:/etc/caddy/Caddyfile
    networks:
      - caddy_net

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ../.env
    networks:
      - app_net
