FROM golang:1.25

RUN apt-get update \
    && apt-get install -y ca-certificates curl gnupg \
    && mkdir -p /etc/apt/keyrings

WORKDIR /app

RUN go install go.uber.org/mock/mockgen@latest && \
    go install github.com/air-verse/air@latest && \
    go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest && \
    go install -tags 'postgresql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

RUN git config --global --add safe.directory /app

# No CMD or ENTRYPOINT exists as the dev server is started directly
