FROM golang:1.25 AS builder

WORKDIR /app
ADD go.mod go.sum ./
RUN go mod download
RUN mkdir ./bin
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/public apps/public/main.go

FROM alpine:latest AS production

COPY --from=builder /app/bin/public /
ENTRYPOINT [ "/public" ]
