FROM golang:1.24 AS builder

WORKDIR /app
ADD go.mod go.sum ./
RUN go mod download
RUN mkdir ./bin
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o ./bin/admin apps/admin/main.go

FROM alpine:latest AS production

COPY --from=builder /app/bin/admin /
ENTRYPOINT [ "/admin" ]
